#!/usr/bin/env bash
# bootstrap_github.sh — one-time, idempotent setup for the DocGuard autonomous pipeline.
#
# Creates: pipeline labels, the Projects v2 board ("DocGuard Autonomous Pipeline") with
# a Status field (Backlog/Ready/In Progress/In Review/Done), repo merge settings,
# branch protection on main (requires the `quality-gate` CI check), and seeds the backlog.
# Writes resolved IDs to .github/pipeline.env (consumed by board.sh and the workflows).
#
# Requires: gh authenticated with scopes: repo, project (run `gh auth refresh -s project,read:project`).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$ROOT/.github/pipeline.env"
PROJECT_TITLE="DocGuard Autonomous Pipeline"
STAGES=("Backlog" "Ready" "In Progress" "In Review" "Done")

note() { printf '\033[1;34m• %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$*" >&2; }

# ── 0. Preflight ────────────────────────────────────────────────────────────
note "Checking gh auth & scopes"
gh auth status >/dev/null 2>&1 || { warn "Not authenticated. Run: gh auth login -h github.com"; exit 1; }
if ! gh auth status 2>&1 | grep -qiE 'project'; then
  warn "Token is missing the 'project' scope. Run: gh auth refresh -h github.com -s project,read:project,repo,workflow"
  warn "Continuing — project-board steps may fail until the scope is added."
fi

REPO_JSON=$(gh repo view --json name,owner,nameWithOwner)
OWNER=$(echo "$REPO_JSON" | jq -r '.owner.login')
REPO_NWO=$(echo "$REPO_JSON" | jq -r '.nameWithOwner')
ok "Repo: $REPO_NWO (owner: $OWNER)"

# ── 1. Labels ───────────────────────────────────────────────────────────────
note "Ensuring pipeline labels"
ensure_label() { gh label create "$1" --color "$2" --description "$3" --force >/dev/null 2>&1 && ok "label $1" || warn "label $1 (exists or failed)"; }
ensure_label "ai-pipeline"          "5319e7" "Created/driven by the autonomous pipeline"
ensure_label "ai-reviewed"          "0e8a16" "AI reviewer has run on this PR"
ensure_label "ai-approved"          "0e8a16" "AI reviewer found no blocking issues"
ensure_label "ai-changes-requested" "d93f0b" "AI reviewer requested changes — triggers AI Fix"
ensure_label "blocked"              "b60205" "Autonomous fix budget exhausted; needs a human"
for n in 1 2 3; do ensure_label "ai-fix-attempt-$n" "ededed" "AI Fix attempt #$n"; done

# ── 2. Project board ────────────────────────────────────────────────────────
note "Ensuring Projects v2 board: $PROJECT_TITLE"
PNUM=$(gh project list --owner "$OWNER" --format json --limit 100 2>/dev/null \
        | jq -r --arg t "$PROJECT_TITLE" '.projects[] | select(.title==$t) | .number' | head -1 || true)
if [[ -z "${PNUM:-}" ]]; then
  PNUM=$(gh project create --owner "$OWNER" --title "$PROJECT_TITLE" --format json | jq -r '.number')
  ok "Created project #$PNUM"
else
  ok "Project already exists: #$PNUM"
fi
PID=$(gh project view "$PNUM" --owner "$OWNER" --format json | jq -r '.id')

# Stage field — a dedicated single-select field we fully control (avoids fighting the
# built-in "Status" field, whose options can't be reliably set via the CLI).
STAGE_FIELD_NAME="Stage"
FIELDS_JSON=$(gh project field-list "$PNUM" --owner "$OWNER" --format json --limit 50)
SFID=$(echo "$FIELDS_JSON" | jq -r --arg n "$STAGE_FIELD_NAME" '.fields[] | select(.name==$n) | .id' | head -1)
if [[ -z "${SFID:-}" || "$SFID" == "null" ]]; then
  note "Creating '$STAGE_FIELD_NAME' field with options: ${STAGES[*]}"
  gh project field-create "$PNUM" --owner "$OWNER" --name "$STAGE_FIELD_NAME" \
     --data-type SINGLE_SELECT --single-select-options "$(IFS=,; echo "${STAGES[*]}")" >/dev/null
  FIELDS_JSON=$(gh project field-list "$PNUM" --owner "$OWNER" --format json --limit 50)
  SFID=$(echo "$FIELDS_JSON" | jq -r --arg n "$STAGE_FIELD_NAME" '.fields[] | select(.name==$n) | .id' | head -1)
  ok "Created '$STAGE_FIELD_NAME' field"
else
  ok "'$STAGE_FIELD_NAME' field already exists"
fi

# ── 3. Write pipeline.env ───────────────────────────────────────────────────
note "Writing $ENV_FILE"
{
  echo "# Generated by scripts/pipeline/bootstrap_github.sh — do not edit by hand."
  echo "PROJECT_OWNER=$OWNER"
  echo "PROJECT_NUMBER=$PNUM"
  echo "PROJECT_ID=$PID"
  echo "STATUS_FIELD_ID=$SFID"
  echo "STATUS_FIELD_NAME=$STAGE_FIELD_NAME"
  echo "$FIELDS_JSON" | jq -r --arg n "$STAGE_FIELD_NAME" '.fields[] | select(.name==$n) | .options[]? |
    "STATUS_OPT_\(.name | ascii_upcase | gsub(" ";"_"))=\(.id)"'
} > "$ENV_FILE"
ok "Wrote IDs for $(grep -c '^STATUS_OPT_' "$ENV_FILE") stages"

# ── 4. Repo merge settings (needed for native auto-merge) ───────────────────
note "Enabling auto-merge + squash + auto-delete branches"
gh api -X PATCH "repos/$REPO_NWO" \
  -F allow_auto_merge=true -F allow_squash_merge=true -F delete_branch_on_merge=true >/dev/null \
  && ok "Repo merge settings updated" || warn "Could not update repo settings (need admin)"

# ── 5. Branch protection on main (require quality-gate) ─────────────────────
note "Protecting main: require 'quality-gate' status check"
# The protection endpoint requires a full JSON body with explicit nulls; the
# `-f key=value` form can't send null, so pipe a JSON document via --input.
printf '%s' '{"required_status_checks":{"strict":true,"contexts":["quality-gate"]},"enforce_admins":false,"required_pull_request_reviews":null,"restrictions":null}' \
  | gh api -X PUT "repos/$REPO_NWO/branches/main/protection" --input - >/dev/null 2>&1 \
  && ok "Branch protection set (requires quality-gate)" \
  || warn "Branch protection not set — needs admin, or private repo on a free plan (see docs/ai-pipeline.md)."

# ── 6. Seed backlog ─────────────────────────────────────────────────────────
note "Seeding backlog (only if board is empty)"
EXISTING=$(gh project item-list "$PNUM" --owner "$OWNER" --format json --limit 5 | jq '.items | length')
if [[ "$EXISTING" == "0" ]]; then
  while IFS= read -r line; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    bash "$ROOT/scripts/pipeline/board.sh" add "$line" "Backlog" >/dev/null && ok "seeded: $line"
  done < "$ROOT/scripts/pipeline/seed_features.txt"
else
  warn "Board already has items; skipping seed."
fi

echo
ok "Bootstrap complete. Next: set the CLAUDE_CODE_OAUTH_TOKEN (and optional PIPELINE_PROJECT_TOKEN) secrets,"
echo "   then move a board item to 'Ready' and run the pipeline. See docs/ai-pipeline.md."
